/**
 * Database Configuration
 * PostgreSQL (Neon-compatible) setup and schema initialization
 */

const { Pool } = require('pg');
const bcrypt = require('bcryptjs');

function normalizeConnectionString(rawConnectionString) {
    if (!rawConnectionString) return '';

    try {
        const parsed = new URL(rawConnectionString);
        const sslMode = (parsed.searchParams.get('sslmode') || '').toLowerCase();
        const hasLibpqCompat = parsed.searchParams.has('uselibpqcompat');

        if (sslMode === 'require' && !hasLibpqCompat) {
            parsed.searchParams.set('uselibpqcompat', 'true');
            return parsed.toString();
        }

        return rawConnectionString;
    } catch {
        // Fallback for non-standard connection strings.
        if (/sslmode=require/i.test(rawConnectionString) && !/uselibpqcompat=/i.test(rawConnectionString)) {
            const separator = rawConnectionString.includes('?') ? '&' : '?';
            return `${rawConnectionString}${separator}uselibpqcompat=true`;
        }
        return rawConnectionString;
    }
}

const connectionString = normalizeConnectionString(process.env.DATABASE_URL || '');
const shouldUseSsl =
    process.env.PGSSL === 'true' ||
    process.env.PGSSLMODE === 'require' ||
    connectionString.includes('sslmode=require');

const poolConfig = connectionString
    ? {
        connectionString,
        ssl: shouldUseSsl ? { rejectUnauthorized: false } : false
    }
    : {
        host: process.env.PGHOST || 'localhost',
        port: Number(process.env.PGPORT || 5432),
        user: process.env.PGUSER || 'postgres',
        password: process.env.PGPASSWORD || '',
        database: process.env.PGDATABASE || 'ezfix',
        ssl: shouldUseSsl ? { rejectUnauthorized: false } : false
    };

const pool = new Pool(poolConfig);

pool.on('error', (err) => {
    console.error('Unexpected PostgreSQL pool error:', err);
});

function toPgPlaceholders(sql) {
    let i = 0;
    return sql.replace(/\?/g, () => {
        i += 1;
        return `$${i}`;
    });
}

function shouldReturnInsertedId(sql) {
    if (!/^\s*insert\s+into\s+/i.test(sql)) return false;
    if (/\sreturning\s+/i.test(sql)) return false;

    const match = sql.match(/^\s*insert\s+into\s+([a-z_][a-z0-9_]*)/i);
    if (!match) return false;

    const table = match[1].toLowerCase();
    const idTables = new Set([
        'users',
        'orders',
        'order_items',
        'cart_items',
        'custom_builds',
        'admin_users',
        'chat_messages',
        'invoices'
    ]);

    return idTables.has(table);
}

const db = {
    async runAsync(sql, params = []) {
        const baseSql = toPgPlaceholders(sql);
        const queryText = shouldReturnInsertedId(baseSql)
            ? `${baseSql} RETURNING id`
            : baseSql;

        const result = await pool.query(queryText, params);
        const insertedId = result.rows && result.rows[0] && result.rows[0].id
            ? Number(result.rows[0].id)
            : null;

        return {
            lastID: insertedId,
            changes: result.rowCount || 0
        };
    },

    async getAsync(sql, params = []) {
        const result = await pool.query(toPgPlaceholders(sql), params);
        return result.rows[0];
    },

    async allAsync(sql, params = []) {
        const result = await pool.query(toPgPlaceholders(sql), params);
        return result.rows || [];
    },

    query(sql, params = []) {
        return pool.query(toPgPlaceholders(sql), params);
    },

    close() {
        return pool.end();
    }
};

async function initializeDatabase() {
    try {
        await pool.query('SELECT 1');
        console.log('Connected to PostgreSQL database');

        const createTablesSql = [
            `CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                email TEXT,
                role TEXT DEFAULT 'customer',
                permissions TEXT DEFAULT '[]',
                reset_token TEXT,
                reset_expires TIMESTAMPTZ,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE IF NOT EXISTS orders (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_number TEXT UNIQUE NOT NULL,
                user_id INTEGER REFERENCES users(id),
                customer_name TEXT NOT NULL,
                customer_email TEXT NOT NULL,
                customer_phone TEXT NOT NULL,
                customer_address TEXT,
                customer_city TEXT,
                customer_zip TEXT,
                country TEXT DEFAULT 'Czech Republic',
                service_type TEXT,
                delivery_fee DOUBLE PRECISION DEFAULT 0,
                payment_method TEXT,
                payment_fee DOUBLE PRECISION DEFAULT 0,
                payment_status TEXT DEFAULT 'pending',
                packeta_point_json TEXT,
                packeta_tracking_number TEXT,
                status TEXT DEFAULT 'pending',
                total DOUBLE PRECISION NOT NULL,
                notes TEXT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE IF NOT EXISTS order_items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                device TEXT NOT NULL,
                brand TEXT NOT NULL,
                model TEXT NOT NULL,
                repair_type TEXT NOT NULL,
                repair_name TEXT NOT NULL,
                price DOUBLE PRECISION NOT NULL,
                printer TEXT,
                filament TEXT,
                color TEXT,
                parts INTEGER,
                file_name TEXT
            )`,
            `CREATE TABLE IF NOT EXISTS cart_items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                device TEXT NOT NULL,
                device_name TEXT NOT NULL,
                brand TEXT NOT NULL,
                brand_name TEXT NOT NULL,
                model TEXT NOT NULL,
                repair_type TEXT NOT NULL,
                repair_name TEXT NOT NULL,
                repair_desc TEXT,
                price DOUBLE PRECISION NOT NULL,
                printer TEXT,
                filament TEXT,
                color TEXT,
                parts INTEGER,
                file_name TEXT,
                added_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE IF NOT EXISTS custom_builds (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                description TEXT,
                parts_json TEXT NOT NULL,
                total_price DOUBLE PRECISION,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE IF NOT EXISTS admin_users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                permissions TEXT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE IF NOT EXISTS catalog (
                key TEXT PRIMARY KEY,
                data TEXT NOT NULL,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE IF NOT EXISTS chat_sessions (
                id TEXT PRIMARY KEY,
                visitor_id TEXT,
                customer_name TEXT,
                customer_email TEXT,
                help_topic TEXT,
                assigned_admin_id INTEGER,
                assigned_admin_name TEXT,
                status TEXT DEFAULT 'open',
                last_message_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE IF NOT EXISTS chat_messages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id TEXT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
                sender_type TEXT NOT NULL,
                sender_name TEXT,
                message TEXT NOT NULL,
                is_read_admin BOOLEAN DEFAULT FALSE,
                is_read_user BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE IF NOT EXISTS invoices (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                invoice_number TEXT UNIQUE NOT NULL,
                order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
                customer_name TEXT NOT NULL,
                customer_email TEXT,
                description TEXT,
                amount DOUBLE PRECISION NOT NULL,
                currency TEXT DEFAULT 'CZK',
                status TEXT DEFAULT 'issued',
                due_date DATE,
                scan_file_url TEXT,
                notes TEXT,
                created_by_user_id INTEGER REFERENCES users(id),
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )`
        ];

        for (const sql of createTablesSql) {
            await pool.query(sql);
        }

        const compatibilityMigrations = [
            `ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token TEXT`,
            `ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_expires TIMESTAMPTZ`,
            `ALTER TABLE users ADD COLUMN IF NOT EXISTS permissions TEXT DEFAULT '[]'`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_city TEXT`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_zip TEXT`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'Czech Republic'`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_fee DOUBLE PRECISION DEFAULT 0`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_fee DOUBLE PRECISION DEFAULT 0`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending'`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS packeta_point_json TEXT`,
            `ALTER TABLE orders ADD COLUMN IF NOT EXISTS packeta_tracking_number TEXT`,
            `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS printer TEXT`,
            `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS filament TEXT`,
            `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS color TEXT`,
            `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS parts INTEGER`,
            `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS file_name TEXT`,
            `ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS printer TEXT`,
            `ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS filament TEXT`,
            `ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS color TEXT`,
            `ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS parts INTEGER`,
            `ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS file_name TEXT`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS customer_name TEXT`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS customer_email TEXT`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS help_topic TEXT`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS assigned_admin_id INTEGER`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS assigned_admin_name TEXT`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'open'`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS last_message_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS typing_user_name TEXT`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS typing_user_at TIMESTAMPTZ`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS typing_admin_name TEXT`,
            `ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS typing_admin_at TIMESTAMPTZ`,
            `ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS is_read_admin BOOLEAN DEFAULT FALSE`,
            `ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS is_read_user BOOLEAN DEFAULT FALSE`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS customer_email TEXT`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS description TEXT`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'CZK'`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'issued'`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS due_date DATE`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS scan_file_url TEXT`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS notes TEXT`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_by_user_id INTEGER REFERENCES users(id)`,
            `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP`
        ];

        for (const sql of compatibilityMigrations) {
            await pool.query(sql);
        }

        await pool.query('CREATE INDEX IF NOT EXISTS idx_chat_messages_session_created ON chat_messages(session_id, created_at DESC)');
        await pool.query('CREATE INDEX IF NOT EXISTS idx_chat_messages_unread_admin ON chat_messages(session_id, is_read_admin, sender_type)');
        await pool.query('CREATE INDEX IF NOT EXISTS idx_chat_sessions_last_message ON chat_sessions(last_message_at DESC)');

        const bootstrapAdminPassword = process.env.BOOTSTRAP_ADMIN_PASSWORD || process.env.ADMIN_PASSWORD;
        const bootstrapAdminUsername = process.env.BOOTSTRAP_ADMIN_USERNAME || process.env.ADMIN_USERNAME || 'admin';

        if (bootstrapAdminPassword) {
            const hashedPassword = bcrypt.hashSync(bootstrapAdminPassword, 10);
            await pool.query(
                `INSERT INTO users (username, password_hash, email, role)
                 VALUES ($1, $2, $3, 'manager')
                 ON CONFLICT (username) DO UPDATE
                 SET
                    password_hash = EXCLUDED.password_hash,
                    role = 'manager',
                    updated_at = CURRENT_TIMESTAMP`,
                [bootstrapAdminUsername, hashedPassword, `${bootstrapAdminUsername}@ezfix.local`]
            );
            console.log(`Bootstrap manager user ensured/updated (${bootstrapAdminUsername})`);
        } else {
            console.log('Skipping bootstrap manager user creation (no BOOTSTRAP_ADMIN_PASSWORD/ADMIN_PASSWORD set)');
        }

        await pool.query(`UPDATE users SET role = 'manager' WHERE role = 'admin'`);

        const ownerUsername = (process.env.OWNER_USERNAME || '').trim().toLowerCase();
        if (ownerUsername) {
            await pool.query(
                `UPDATE users SET role = 'owner' WHERE LOWER(username) = $1`,
                [ownerUsername]
            );
        }

        const ownerPassword = process.env.OWNER_PASSWORD;
        if (ownerUsername && ownerPassword) {
            const ownerHash = bcrypt.hashSync(ownerPassword, 10);
            await pool.query(
                `INSERT INTO users (username, password_hash, email, role)
                 VALUES ($1, $2, $3, 'owner')
                 ON CONFLICT (username) DO UPDATE
                 SET
                    password_hash = EXCLUDED.password_hash,
                    role = 'owner',
                    updated_at = CURRENT_TIMESTAMP`,
                [ownerUsername, ownerHash, `${ownerUsername}@ezfix.local`]
            );
            console.log(`Owner account ensured/updated (${ownerUsername})`);
        } else if (ownerUsername && !ownerPassword) {
            console.log('OWNER_USERNAME is set but OWNER_PASSWORD is missing; owner password not reset');
        }

        console.log('Database tables initialized successfully');
    } catch (err) {
        console.error('Database initialization failed:', err);
        throw err;
    }
}

module.exports = {
    db,
    initializeDatabase
};
